### ISSUE TITLE
Rotating is broken on my laptop

### ISSUE THREAD

**Issue by cnnradams** [AstechzGO/Luminescent#94] opened 2016-01-22 17:44 UTC
It stays between the 90 and 180 angle, and it does not follow the mouse at full speed

**Comment by ryanlarkin** [comment] 2016-01-22 18:06
I assume you are using the latest code?

**Comment by ryanlarkin** [comment] 2016-01-22 18:07
Are you in fullscreen?

**Comment by cnnradams** [comment] 2016-01-22 18:07
The latest code in major-update yes

**Comment by cnnradams** [comment] 2016-01-22 18:07
I'll show you at robotics if you want

**Comment by cnnradams** [comment] 2016-01-22 18:12
No wasnt

**Comment by ryanlarkin** [comment] 2016-01-22 18:15
Do you have multiple monitors connected?

**Comment by ryanlarkin** [comment] 2016-01-22 18:16
I won't be at robotics tonight but I think I'll be there tomorrow.

**Comment by ryanlarkin** [comment] 2016-01-22 21:10
For now, I'll set this to "can't reproduce". Also, what's your screen resolution, and why did you create the bugfix branch?

**Comment by ryanlarkin** [comment] 2016-01-22 21:12
Actually, I got the bug by changing my resolution.

**Comment by ryanlarkin** [comment] 2016-01-22 21:22
Here's the broken code:

```
x = x + xpos.get(0) + ((Camera.CAMERA_WIDTH / 2) - xpos.get(0) - DisplayUtils.getDisplayWidth() / 2);
y = -y + DisplayUtils.monitorHeight - ypos.get(0) - ((Camera.CAMERA_HEIGHT / 2) - ypos.get(0) - DisplayUtils.getDisplayHeight() / 2);
```

**Comment by ryanlarkin** [comment] 2016-01-22 21:28
I used Camera.CAMERA_WIDTH/HEIGHT instead of monitorWidth/Height. Committing fix now.

**Comment by ryanlarkin** [comment] 2016-01-22 21:36
Could you please test the changes, and close if the fix works?

**Comment by ryanlarkin** [comment] 2016-01-23 16:23
@Stealth2994, I assume this is fixed, closing.

**Closed as completed by ryanlarkin** 2016-01-23 16:23 UTC
Labels: bug, confirmed
